# Generated by Django 3.0.2 on 2020-01-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('biology', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('harvest', models.CharField(max_length=200)),
                ('harvest_type', models.CharField(max_length=200)),
                ('best_harvest', models.CharField(max_length=200)),
                ('farming_methods', models.CharField(max_length=200)),
                ('fishing_rate', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('health_benefits', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
